name: Deploy ASME Web 

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: asme-website/package-lock.json

      - name: Install
        run: npm ci
        working-directory: asme-website

      - name: Lint
        run: npm run lint
        working-directory: asme-website

      # - name: Test
      #   run: npm run test
      #   working-directory: asme-website

      - name: Build
        run: npm run build
        working-directory: asme-website

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./asme-website/dist
